import GetLang from 'Com/get-lang';
import Image from 'next/image';
import Script from 'next/script';
import './globals.css';
import logo from 'Pub/foricon-f-2.png'

export const metadata = {
    title: 'Foricon',
    // description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <head>
                <link href='//fonts.googleapis.com' rel='preconnect'/>
                <link crossOrigin='' href='//fonts.gstatic.com' rel='preconnect'/>
                <link href='//fonts.googleapis.com/css2?family=Afacad:ital,wght@0,400..700;1,400..700&family=Fira+Code:wght@300..700&family=Source+Code+Pro:ital,wght@0,200..900;1,200..900&family=DM+Mono:ital,wght@0,300;0,400;0,500;1,300;1,400;1,500&family=Kode+Mono:wght@400..700&family=Nova+Mono&family=Sono:wght,MONO@200..800,1&family=Xanh+Mono:ital@0;1' rel='stylesheet'/>
            </head>
            <body>
                <Script
                    data-uid='ud4lP1mhq4XvynG7qUlcsAxi0Q02'
                    src='//foricon-src.github.io/main/loader.js'
                    strategy='afterInteractive'
                />
                <header>
                    <div>
                        <a href='/' name='logo'>
                            <Image src={logo} alt='Foricon logo'></Image>
                        </a>
                        <a href='/changelog' name='version'>Beta 3.0</a>
                    </div>
                    <ul className='btn-list' name='center'>
                        <li>
                            <lang value='en'>Home</lang>
                            <lang value='vi'>Trang chủ</lang>
                            <lang value='fr'>Page d&apos;accueil</lang>
                            <lang value='it'>Pagina iniziale</lang>
                            <lang value='kr'>홈페이지</lang>
                            <lang value='ja'>ホームページ</lang>
                            <lang value='de'>Startseite</lang>
                            <lang value='nl'>Startpagina</lang>
                            <lang value='dk'>Hjemmeside</lang>
                            <lang value='pt'>Pagina inicial</lang>
                            <lang value='es'>Pagina de inicio</lang>
                            <lang value='ru'>Дом</lang>
                        </li>
                        <li></li>
                        <li></li>
                        <li></li>
                    </ul>
                    <ul className='btn-list' name='right'>
                        <li className='chip bottom'>
                            <f-icon icon='translate' i-s='outline'></f-icon>
                            <lang value='en'>Languages</lang>
                            <lang value='vi'>Ngôn ngữ</lang>
                            <lang value='fr'>Langues</lang>
                            <lang value='it'>Le lingue</lang>
                            <lang value='kr'>언어</lang>
                            <lang value='ja'>言語</lang>
                            <lang value='de'>Sprachen</lang>
                            <lang value='nl'>Talen</lang>
                            <lang value='dk'>Sprog</lang>
                            <lang value='pt'>Línguas</lang>
                            <lang value='es'>Idiomas</lang>
                            <lang value='ru'>Языки</lang>
                        </li>
                        <li className='chip bottom'>
                            <f-icon icon='bars' i-s='outline'></f-icon>
                            <lang value='en'>All</lang>
                            <lang value='vi'>Tất cả</lang>
                            <lang value='fr'>Tout</lang>
                            <lang value='it'>Tutto</lang>
                            <lang value='kr'>모두</lang>
                            <lang value='ja'>全て</lang>
                            <lang value='de'>Alle</lang>
                            <lang value='nl'>Alle</lang>
                            <lang value='dk'>Alle</lang>
                            <lang value='pt'>Tudo</lang>
                            <lang value='es'>Todo</lang>
                            <lang value='ru'>Все</lang>
                        </li>
                        <li className='chip bottom line'>
                            <f-icon icon='arrow-right-to-bracket' i-s='outline'></f-icon>
                            <span/>
                        </li>
                    </ul>
                    <ul className='btn-list' name='all'>
                        <li>Foricon Plus</li>
                        <li className='line'>
                            <lang value='en'>Home</lang>
                            <lang value='vi'>Trang chủ</lang>
                            <lang value='fr'>Page d&apos;accueil</lang>
                            <lang value='it'>Pagina iniziale</lang>
                            <lang value='kr'>홈페이지</lang>
                            <lang value='ja'>ホームページ</lang>
                            <lang value='de'>Startseite</lang>
                            <lang value='nl'>Startpagina</lang>
                            <lang value='dk'>Hjemmeside</lang>
                            <lang value='pt'>Pagina inicial</lang>
                            <lang value='es'>Pagina de inicio</lang>
                            <lang value='ru'>Дом</lang>
                        </li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                    </ul>
                </header>
                {children}
            </body>
            <GetLang/>
        </html>
    );
}
